#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Console App Demo', '0.0.1');

$app->add(new SpeakCommand);

$app->run();